### ISSUE TITLE
Value not loaded

### ISSUE THREAD

**Issue by codetailor-eu** [coding-monkeys-bv/laravel-nova-inline-text#1]
Thanks for this great plugin - I would really like to use it on Nova 4, but it does not pick up the value from the database but instead always just shows the placeholder.

I tried it like this:

InlineText::make('Price', 'amount')->hideWhenCreating() ->type('number')
                    ->placeholder('0.00')
                    ->successMessage('The Price has been updated!')
                    ->displayUsing(function ($value) {
                        return $value;
                    }),

But no matter which type I use, the field is always empty when I load the resource index.

**Comment by voicecode-bv** [comment]
@itbul Thank you! For some reason I did not get a notification of your ticket. I'm publishing an update now which should solve this issue.
